
"""optimize_db_schema
Revision ID: 11b8e3e66b77
Revises: 1e7bb4d71e2e
Create Date: 2026-07-14 14:30:15.303113
"""

# alembic revision identifiers
revision = '11b8e3e66b77'
down_revision = '1e7bb4d71e2e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('match_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_answers_match_id'), 'answers', ['match_id'], unique=False)
    op.create_unique_constraint('uq_player_question_answer', 'answers', ['question_id', 'player_id'])
    op.create_foreign_key(None, 'answers', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answers', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_column('matches', 'leaderboard')
    op.add_column('questions', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('difficulty', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('text', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('questions', sa.Column('correct_index', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.drop_column('questions', 'question_json')
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_column('questions', 'correct_index')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'text')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'topic')
    op.add_column('matches', sa.Column('leaderboard', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint('uq_player_question_answer', 'answers', type_='unique')
    op.drop_index(op.f('ix_answers_match_id'), table_name='answers')
    op.drop_column('answers', 'match_id')
    # ### end Alembic commands ###
