
"""initial
Revision ID: 11e8a5040166
Revises: b8522aab4ac9
Create Date: 2026-07-05 19:02:47.609893
"""

# alembic revision identifiers
revision = '11e8a5040166'
down_revision = 'b8522aab4ac9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
