"""autogen initial
Revision ID: 2476afd8efb8
Revises: 0001_initial
Create Date: 2026-07-05 15:40:16.453581
"""
# revision identifiers, used by Alembic.
revision = '2476afd8efb8'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
