
"""add created_at to matches
Revision ID: 6ae400a1dd89
Revises: 11b8e3e66b77
Create Date: 2026-07-14 23:41:44.494531
"""

# alembic revision identifiers
revision = '6ae400a1dd89'
down_revision = '11b8e3e66b77'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'created_at')
    # ### end Alembic commands ###
