
"""autogen next
Revision ID: b8522aab4ac9
Revises: 2476afd8efb8
Create Date: 2026-07-05 15:42:34.637232
"""

# alembic revision identifiers
revision = 'b8522aab4ac9'
down_revision = '2476afd8efb8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
